version: "3.8"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=microservices
      - RABBITMQ_URL=amqp://rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ./logs/mq-events:/app/logs

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=microservices
      - RABBITMQ_URL=amqp://rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./logs/mq-events:/app/logs

  auth-service:
    build: ./services/auth-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - JWT_SECRET=supersecret
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - order-service
    environment:
      - PORT=3000
      - AUTH_URL=http://auth-service:3003
      - USER_SERVICE_URL=http://user-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10

  tester:
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    depends_on:
      gateway-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    environment:
      - GATEWAY_URL=http://gateway-service:3000
      - AUTH_URL=http://auth-service:3003
      - MQ_EVENT_LOGS_URL=/app/logs/mq-events/consumer-events.log
    command: ["npm", "test"]
    profiles:
      - test
    volumes:
      - ./logs/mq-events:/app/logs/mq-events

volumes:
  pgdata:
